Fix handling urls without hostname
For weird URLs like "http:something" host is None but scheme is "http".
I believe we should not fail for such urls.

Before the patch we had the following exception:
```
Traceback (most recent call last):
  File "referer_parser/test/__init__.py", line 204, in test_no_host
    r = Referer("http:some/path")
  File "referer_parser/__init__.py", line 57, in __init__
    referer = self._lookup_referer(ref_host, ref_uri.path, True)
  File "referer_parser/__init__.py", line 79, in _lookup_referer
    referer = self.referers[ref_host + ref_path]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```